# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 19:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20161114_1655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='league',
            old_name='players',
            new_name='player',
        ),
        migrations.AddField(
            model_name='matchup',
            name='league',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sports.League'),
            preserve_default=False,
        ),
    ]
