# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0003_auto_20161114_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.RemoveField(
            model_name='team',
            name='squad',
        ),
        migrations.AddField(
            model_name='matchup',
            name='away_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchup',
            name='home_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='squad',
            name='roster',
            field=models.ManyToManyField(blank=True, to='sports.Team'),
        ),
        migrations.AddField(
            model_name='team',
            name='week_1',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_10',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_11',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_12',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_13',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_14',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_15',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_16',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_17',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_2',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_3',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_4',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_5',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_6',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_7',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_8',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='week_9',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
