# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 21:40
from __future__ import unicode_literals

from django.db import migrations
import csv

def add_team_data(apps, schema_editor):
    Team = apps.get_model("sports", "Team")
    with open('teams.csv') as infile:
        reader = csv.reader(infile)
        for row in reader:
            Team.objects.create(city=row[0], name=row[1], sport=row[2], pts_last=row[3],
             pts_proj=row[4], week_1=row[5], week_2=row[6], week_3=row[7], week_4=row[8],
             week_5=row[9], week_6=row[10], week_7=row[11], week_8=row[12], week_9=row[13],
             week_10=row[14], week_11=row[15], week_12=row[16], week_13=row[17], week_14=row[18],
             week_15=row[19], week_16=row[20], week_17=row[21])



class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0004_auto_20161114_2139'),
    ]

    operations = [
    #migrations.RunPython(add_team_data)
    ]
