# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 19:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sports', '0005_auto_20161114_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayLeague',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('limit', models.IntegerField()),
                ('live', models.BooleanField(default=False)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
                ('player', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='away_score',
        ),
        migrations.RemoveField(
            model_name='matchup',
            name='home_score',
        ),
    ]
