# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0011_auto_20161116_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='pts',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='score',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
