# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-17 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0012_auto_20161116_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='tag',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
