# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0015_auto_20161118_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='active_squad',
            field=models.ManyToManyField(blank=True, to='sports.Squad'),
        ),
        migrations.AddField(
            model_name='score',
            name='game_time',
            field=models.CharField(default='(FINAL)', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
