# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0017_remove_league_weekly_matchup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sports.League')),
            ],
        ),
    ]
