# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0021_auto_20161128_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='squad',
            name='logo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
